// ============================================
// Centralised dropdown options
// ============================================
// Each array uses { value: string; label: string } format,
// compatible with both <Select> and <Combobox>.

export const cropTypeOptions: { value: string; label: string }[] = [
  { value: 'wheat', label: 'Wheat' },
  { value: 'barley', label: 'Barley' },
  { value: 'oats', label: 'Oats' },
  { value: 'maize', label: 'Maize' },
  { value: 'rice', label: 'Rice' },
  { value: 'rye', label: 'Rye' },
  { value: 'sorghum', label: 'Sorghum' },
  { value: 'millet', label: 'Millet' },
  { value: 'rapeseed', label: 'Rapeseed (Canola)' },
  { value: 'soybeans', label: 'Soybeans' },
  { value: 'sunflower', label: 'Sunflower' },
  { value: 'potatoes', label: 'Potatoes' },
  { value: 'sugar-beet', label: 'Sugar Beet' },
  { value: 'sugar-cane', label: 'Sugar Cane' },
  { value: 'tomatoes', label: 'Tomatoes' },
  { value: 'lettuce', label: 'Lettuce' },
  { value: 'onions', label: 'Onions' },
  { value: 'carrots', label: 'Carrots' },
  { value: 'apples', label: 'Apples' },
  { value: 'pears', label: 'Pears' },
  { value: 'berries', label: 'Berries' },
  { value: 'grapes', label: 'Grapes' },
  { value: 'citrus', label: 'Citrus' },
  { value: 'silage', label: 'Silage' },
  { value: 'clover', label: 'Clover' },
  { value: 'cotton', label: 'Cotton' },
  { value: 'coffee', label: 'Coffee' },
  { value: 'cocoa', label: 'Cocoa' },
  { value: 'tea', label: 'Tea' },
  { value: 'olives', label: 'Olives' },
];

export const livestockTypeOptions: { value: string; label: string }[] = [
  { value: 'cattle-dairy', label: 'Cattle (Dairy)' },
  { value: 'cattle-beef', label: 'Cattle (Beef)' },
  { value: 'sheep', label: 'Sheep' },
  { value: 'goats', label: 'Goats' },
  { value: 'pigs', label: 'Pigs' },
  { value: 'chickens-layers', label: 'Chickens (Layers)' },
  { value: 'chickens-broilers', label: 'Chickens (Broilers)' },
  { value: 'turkeys', label: 'Turkeys' },
  { value: 'ducks', label: 'Ducks' },
  { value: 'geese', label: 'Geese' },
  { value: 'horses', label: 'Horses' },
  { value: 'deer', label: 'Deer' },
  { value: 'alpacas', label: 'Alpacas' },
  { value: 'rabbits', label: 'Rabbits' },
  { value: 'bees', label: 'Bees' },
];

export const fertiliserTypeOptions: { value: string; label: string }[] = [
  { value: 'urea', label: 'Urea' },
  { value: 'ammonium-nitrate', label: 'Ammonium Nitrate' },
  { value: 'can', label: 'CAN (Calcium Ammonium Nitrate)' },
  { value: 'npk-compound', label: 'NPK Compound' },
  { value: 'dap', label: 'DAP (Diammonium Phosphate)' },
  { value: 'map', label: 'MAP (Monoammonium Phosphate)' },
  { value: 'potassium-chloride', label: 'Potassium Chloride (MOP)' },
  { value: 'single-superphosphate', label: 'Single Superphosphate' },
  { value: 'triple-superphosphate', label: 'Triple Superphosphate' },
  { value: 'farmyard-manure', label: 'Farmyard Manure' },
  { value: 'slurry', label: 'Slurry' },
  { value: 'compost', label: 'Compost' },
  { value: 'biosolids', label: 'Biosolids' },
  { value: 'seaweed-extract', label: 'Seaweed Extract' },
  { value: 'bone-meal', label: 'Bone Meal' },
  { value: 'fish-meal', label: 'Fish Meal' },
  { value: 'green-manure', label: 'Green Manure' },
  { value: 'lime', label: 'Lime' },
  { value: 'gypsum', label: 'Gypsum' },
  { value: 'biochar', label: 'Biochar' },
];

export const landUseTypeOptions: { value: string; label: string }[] = [
  { value: 'arable-cropland', label: 'Arable Cropland' },
  { value: 'permanent-grassland', label: 'Permanent Grassland' },
  { value: 'temporary-grassland', label: 'Temporary Grassland' },
  { value: 'horticulture', label: 'Horticulture' },
  { value: 'orchard', label: 'Orchard' },
  { value: 'vineyard', label: 'Vineyard' },
  { value: 'forestry', label: 'Forestry' },
  { value: 'wetland', label: 'Wetland' },
  { value: 'hedgerows', label: 'Hedgerows' },
  { value: 'buffer-strips', label: 'Buffer Strips' },
  { value: 'set-aside', label: 'Set-aside' },
  { value: 'built-up-farmstead', label: 'Built-up (Farmstead)' },
  { value: 'water-bodies', label: 'Water Bodies' },
  { value: 'peatland', label: 'Peatland' },
  { value: 'silvopasture', label: 'Silvopasture' },
];

export const packagingMaterialOptions: { value: string; label: string }[] = [
  { value: 'cardboard', label: 'Cardboard' },
  { value: 'paper', label: 'Paper' },
  { value: 'ldpe-film', label: 'LDPE Film' },
  { value: 'hdpe', label: 'HDPE' },
  { value: 'pet', label: 'PET' },
  { value: 'polypropylene', label: 'Polypropylene' },
  { value: 'glass', label: 'Glass' },
  { value: 'aluminium', label: 'Aluminium' },
  { value: 'tin-steel', label: 'Tin/Steel' },
  { value: 'wood-pallets', label: 'Wood/Pallets' },
  { value: 'bioplastic', label: 'Bioplastic' },
  { value: 'foam-eps', label: 'Foam (EPS)' },
  { value: 'jute-hessian', label: 'Jute/Hessian' },
  { value: 'wax-coated-board', label: 'Wax-coated Board' },
  { value: 'recycled-plastic', label: 'Recycled Plastic' },
];

export const transportModeOptions: { value: string; label: string }[] = [
  { value: 'road-hgv', label: 'Road (HGV)' },
  { value: 'road-lgv', label: 'Road (LGV/Van)' },
  { value: 'road-electric-van', label: 'Road (Electric Van)' },
  { value: 'rail', label: 'Rail' },
  { value: 'sea-freight', label: 'Sea Freight' },
  { value: 'air-freight', label: 'Air Freight' },
  { value: 'inland-waterway', label: 'Inland Waterway' },
  { value: 'pipeline', label: 'Pipeline' },
  { value: 'bicycle-cargo-bike', label: 'Bicycle/Cargo Bike' },
  { value: 'walking-manual', label: 'Walking/Manual' },
];

export const materialCategoryOptions: { value: string; label: string }[] = [
  { value: 'raw-materials', label: 'Raw Materials' },
  { value: 'chemicals', label: 'Chemicals' },
  { value: 'fuels', label: 'Fuels' },
  { value: 'lubricants', label: 'Lubricants' },
  { value: 'seeds', label: 'Seeds' },
  { value: 'animal-feed', label: 'Animal Feed' },
  { value: 'bedding-litter', label: 'Bedding/Litter' },
  { value: 'veterinary-products', label: 'Veterinary Products' },
  { value: 'cleaning-agents', label: 'Cleaning Agents' },
  { value: 'ppe', label: 'PPE' },
  { value: 'packaging-materials', label: 'Packaging Materials' },
  { value: 'office-supplies', label: 'Office Supplies' },
  { value: 'construction-materials', label: 'Construction Materials' },
  { value: 'spare-parts', label: 'Spare Parts' },
  { value: 'water-treatment', label: 'Water Treatment' },
];
