import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://ecosystemsunited.com";

  // Static marketing pages
  const staticPages = [
    "",
    "/about",
    "/for-advisors",
    "/see-it-in-action",
    "/articles",
    "/privacy",
    "/modern-sustainability",
    "/framework",
    "/framework/implementation",
    "/framework/stack-1-metrics",
    "/framework/stack-2-efficiency",
    "/framework/stack-3-circularity",
    "/framework/stack-4-resilience",
    "/framework/stack-5-regeneration",
    "/tools",
    "/tools/stack-assessment",
    "/tools/metrics-assessment",
    "/tools/efficiency-assessment",
    "/tools/circularity-assessment",
    "/tools/resilience-assessment",
    "/tools/regeneration-assessment",
    "/tools/soil-health-checklist",
    "/start/buyer-questionnaire",
    "/start/csrd",
    "/start/costs",
  ];

  // All article slugs
  const articleSlugs = [
    "advanced-biofuels",
    "advantages-and-disadvantages-of-ecolabels",
    "advantages-disadvantages-agribusiness",
    "advantages-disadvantages-intercropping",
    "agricultural-drainage",
    "agricultural-irrigation",
    "agricultural-sustainability-checklist",
    "agriculture-vs-agribusiness",
    "agribusiness-supply-chain-explained",
    "agribusiness-technology-trends",
    "agroforestry-economics",
    "biochar-soil-amendment",
    "biodiversity-assessment-farms",
    "biodiversity-net-gain-agriculture",
    "biofuel-sustainability-ranking",
    "biofuel-trends-2025",
    "biofuels-explained",
    "biofuels-in-aviation",
    "biomass-energy-farm",
    "building-baseline",
    "building-esg-response-system",
    "buyer-scope-3-request",
    "buyer-scrutiny",
    "carbon-markets-agriculture",
    "cellulosic-biofuels",
    "cellulosic-vs-traditional-biofuels",
    "challenges-to-ecolabels",
    "circular-economy-explained",
    "circular-supply-chains-food",
    "climate-risk-assessment-farms",
    "closed-loop-nutrient-cycling",
    "companion-planting-introduction",
    "composting-nutrient-cycling-roi",
    "cooperative-models-small-farms",
    "cover-crop-selection-guide",
    "cover-crops-roi",
    "crop-diversification-risk",
    "csrd-vsme-agricultural-suppliers",
    "direct-marketing-small-farms",
    "disadvantages-of-ecolabels",
    "drivers-of-ecolabel-adoption",
    "drought-resilience-water-management",
    "erosion-control-strategies",
    "esg-competitive-advantage",
    "esg-labels-in-2025",
    "esg-reporting-small-farms",
    "farm-insurance-climate-adaptation",
    "farm-succession-planning",
    "farm-waste-to-value",
    "financial-resilience-farm-operations",
    "first-esg-questionnaire",
    "food-deserts-market-opportunity",
    "hedgerow-management-economics",
    "how-to-spot-fake-ecolabels",
    "industrial-food-system-small-farms",
    "intercropping-cereal-legume",
    "intercropping-climate-resilience",
    "intercropping-organic-systems",
    "intercropping-pest-management",
    "intercropping-practices",
    "intercropping-vs-polyculture",
    "introduction-to-intercropping",
    "irrigation-system-planning",
    "land-use-planning-farms",
    "life-cycle-assessment-explained",
    "lose-buyers-without-esg",
    "market-volatility-strategies",
    "measuring-intercropping-effectiveness",
    "missing-esg-data",
    "most-trustworthy-ecolabels",
    "nutrient-management-planning",
    "origins-history-agribusiness",
    "pest-disease-climate-change",
    "pollinator-habitat-farm",
    "precision-irrigation-technology",
    "pros-and-cons-of-advanced-biofuels",
    "rainwater-harvesting-agriculture",
    "ranking-biofuel-sustainability",
    "regenerative-agriculture-economics",
    "regenerative-practices-2025",
    "regenerative-transition-costs",
    "scope-1-2-3-agriculture",
    "small-farm-competitive-strategy",
    "small-farm-financial-planning",
    "small-farm-market-channels",
    "small-farm-value-added-products",
    "small-vs-large-agribusiness",
    "soil-compaction-management",
    "soil-health-business-case",
    "soil-organic-matter-building",
    "soil-testing-guide",
    "subsurface-drainage-design",
    "supply-chain-resilience-agriculture",
    "sustainability-in-agribusiness",
    "the-different-types-of-ecolabels",
    "tillage-systems-compared",
    "value-chains-economic-efficiency",
    "water-quality-management-farms",
    "water-recycling-efficiency",
    "what-are-ecolabels",
    "what-are-small-farms",
    "what-gets-measured",
    "what-is-agribusiness",
    "why-consumers-want-local-food",
  ];

  const now = new Date().toISOString();

  const staticEntries: MetadataRoute.Sitemap = staticPages.map((path) => ({
    url: `${baseUrl}${path}`,
    lastModified: now,
    changeFrequency: path === "" ? "weekly" : "monthly",
    priority: path === "" ? 1.0 : path.startsWith("/framework") ? 0.8 : 0.7,
  }));

  const articleEntries: MetadataRoute.Sitemap = articleSlugs.map((slug) => ({
    url: `${baseUrl}/articles/${slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  return [...staticEntries, ...articleEntries];
}
